### ISSUE TITLE
Using isochron with non time-aware machines within network

### ISSUE THREAD

**Issue by stefan-ramdhan** [vladimiroltean/isochron#16]
I am using isochron to measure asymmetric latencies across a 5G network, with two TSN Endstations on either side of the network. I know 5G isn't your area of expertise, nor was this tool designed for 5G applications. What I'm doing is completely unorthodox; and it's not meant to provide good quality synchronization with linuxptp. But the quality of my measurements are what I care about most.

I know gPTP requires all devices within the synchronization path to be time-aware. Will using isochron to measure to latency between two hardware timestamps (i.e. `R-T`, or propagation delay), where there are multiple non time-aware switches in between the two Endstations, be an accurate measurement of the propagation delay? For reference, when using the P2P mechanism, I'm seeing the pdelay calculated by ptp4l, and the one-way delay calculated by isochron to be pretty different from each other, with isochron's pdelay value (`R-T`) being higher than the `peerMeanPathDelay` calculation from ptp4l. Even when I only have one non time-aware switch in between my GM and slave, I see the `R-T` value is `~4 us` greater than ptp4l's `peerMeanPathDelay`. I would expect ptp4l and isochron to be equally as incorrect, since they both wouldn't account for the residence time within this switch. 

According to this [Meinberg article](https://blog.meinbergglobal.com/2013/09/19/end-end-versus-peer-peer/), if there are non 1588 aware switches in between your GM and slave, they say it's best to use the E2E mechanism. Using E2E with non time-aware switches in our network results in all of the receiver's timestamps (`R`, `r`, `a`) to be `000000000.000000000`. Any ideas why this might be?

Thanks in advance.

**Comment by vladimiroltean** [comment]
> Using E2E with non time-aware switches in our network results in all of the receiver's timestamps (R, r, a) to be 000000000.000000000. Any ideas why this might be?

I guess the isochron test packets are lost and never make it to the receiver. Doesn't the receiver say something about timing out waiting for the rest of the packets, and sending the log anyway?

**Comment by stefan-ramdhan** [comment]
The isochron test packets are making it to the receiver, oddly enough, verified by checking the Wireshark logs. I should make a dissector in Wireshark so I can actually read the packets, because right now I just see a hex string, but I can confirm that the test packets (being sent over UDP) are making it to the receiver, so there is no "time out" message. 

I can post a snippet of a Wireshark log tomorrow, if that helps.

**Comment by vladimiroltean** [comment]
Ok, waiting for you to post the isochron sender and receiver commands and output log, I hope I can reproduce.

**Comment by stefan-ramdhan** [comment]
So, it turns out this had nothing to do with E2E or P2P. Within the 5G network, there are 1 or more routers, and the L2 packets will be dropped at the router, because L2 packets are meant for the same LAN.  The solution was to send isochron test packets over UDP. This worked fine. 

However, neither the isochron receiver nor sender indicated that isochron test packets were not making it to the receiver. This could only be found out when using `isochron report`; where timestamps would be 0 as shown below:



```
sudo isochron report -F test-isochron.dat --printf-args "qTRtrwa" --printf-format "%u %T %T %T %T %T %T\n" -m

1 1690820907.000162155 0.000000000 1690820907.000156742 0.000000000 1690820907.000130239 0.000000000
2 1690820908.000172003 0.000000000 1690820908.000166091 0.000000000 1690820908.000132523 0.000000000
3 1690820909.000167885 0.000000000 1690820909.000161971 0.000000000 1690820909.000129111 0.000000000
4 1690820910.000169235 0.000000000 1690820910.000163248 0.000000000 1690820910.000129336 0.000000000
5 1690820911.000163585 0.000000000 1690820911.000157624 0.000000000 1690820911.000124763 0.000000000
6 1690820912.000170257 0.000000000 1690820912.000164300 0.000000000 1690820912.000130708 0.000000000
7 1690820913.000168748 0.000000000 1690820913.000162762 0.000000000 1690820913.000129059 0.000000000
8 1690820914.000169808 0.000000000 1690820914.000163847 0.000000000 1690820914.000129984 0.000000000
9 1690820915.000168249 0.000000000 1690820915.000162389 0.000000000 1690820915.000128545 0.000000000
10 1690820916.000167945 0.000000000 1690820916.000161993 0.000000000 1690820916.000128966 0.000000000
11 1690820917.000161773 0.000000000 1690820917.000155705 0.000000000 1690820917.000122730 0.000000000
12 1690820918.000162394 0.000000000 1690820918.000156581 0.000000000 1690820918.000123611 0.000000000
13 1690820919.000170814 0.000000000 1690820919.000164873 0.000000000 1690820919.000129815 0.000000000
14 1690820920.000169790 0.000000000 1690820920.000163829 0.000000000 1690820920.000128908 0.000000000
15 1690820921.000172458 0.000000000 1690820921.000166484 0.000000000 1690820921.000131386 0.000000000
Packets not received: 15 (100.000%)
Could not calculate statistics, no packets were received
```


If this is the desired behaviour (i.e. only being able to figure out that isochron test packets aren't making it to the receiver when the run has finished, and you report the values/summary), then isochron wasn't doing anything abnormal. We can close this issue.

**Comment by vladimiroltean** [comment]
Can you please instrument why you aren't seeing this print in the receiver?
https://github.com/vladimiroltean/isochron/blob/master/src/rcv.c#L309
```
"Timed out waiting for data packets, received %lu out of %lu expected\n",
```

**Comment by stefan-ramdhan** [comment]
I can spend some time tomorrow trying to debugging why this isn't printing on the receiver, sure. It may have to do with the fact that we are omitting sync, not sure. For reference, this is the sender command I'm using:
```
sudo isochron send -i enp2s0 -s 64 --client 192.168.6.245 -c 1.0 -t 1 -w  1.0 -Q -F 0-isochron.dat -n 60 -o -O 37 --cpu-mask $((1 << 1)) --sched-fifo --sched-priority 50 -4 -J 192.168.6.245
```
and the receiver:
```
sudo isochron rcv -i enp1s0 -t 1
```

Since I'm leaving soon for vacation, I won't be able to spend too much time on this tomorrow, but I can spend more time after I come back.

**Comment by stefan-ramdhan** [comment]
This ended up not being an issue with isochron, but with my wireless network setup.
