### ISSUE TITLE
Multiple isochron senders from the same host

### ISSUE THREAD

**Issue by JorgeSasiain** [vladimiroltean/isochron#20]
Hello!

I'm trying to test TSN streams coming from Docker containers. Each container runs an `isochron send` instance with a different `stats-port`s, against another host running multiple instances of `isochron-rcv` in all those `stats-port`s.

When multiple sending containers run in parallel, `isochron-rcv` (also executed inside the container immediately after `isochron send` completes) reports the same stats for all of them, apparently corresponding to the stats of the last run container. Please, see below:

Container 1:
```
         Now:   1706089835.860477689
First wakeup:   1706089836.400000000
   Base time:   1706089837.000000000
  Cycle time:            0.800000000
Collecting receiver stats
seqid 1 scheduled for 1706089837.000000000, TX qdisc 0.000000000 sw 0.000000000 hw 0.000000000, RX hw 1706089837.800086703 sw 1706089837.800199604
seqid 2 scheduled for 1706089837.800000000, TX qdisc 0.000000000 sw 0.000000000 hw 0.000000000, RX hw 1706089838.600087102 sw 1706089838.600185371
seqid 3 scheduled for 1706089838.600000000, TX qdisc 0.000000000 sw 0.000000000 hw 0.000000000, RX hw 1706089839.400079604 sw 1706089839.400175236
(...)
```

Container 2:
```
         Now:   1706089837.092443428
First wakeup:   1706089837.200000000
   Base time:   1706089837.800000000
  Cycle time:            0.800000000
Collecting receiver stats
seqid 1 scheduled for 1706089837.800000000, TX qdisc 0.000000000 sw 0.000000000 hw 0.000000000, RX hw 1706089837.800086703 sw 1706089837.800199604
seqid 2 scheduled for 1706089838.600000000, TX qdisc 0.000000000 sw 0.000000000 hw 0.000000000, RX hw 1706089838.600087102 sw 1706089838.600185371
seqid 3 scheduled for 1706089839.400000000, TX qdisc 0.000000000 sw 0.000000000 hw 0.000000000, RX hw 1706089839.400079604 sw 1706089839.400175236
```

In the receiver side, I see several ``Discarding seqid <XX>`` messages, which makes sense to me, as each `isochron-rcv` instance is discarding packets targeting a different port (as explained [here](https://github.com/vladimiroltean/isochron/issues/9#issuecomment-1011094807)). I can disable these messages with the `--quiet` option. However, I also see the following messages:

```
Timed out waiting for data packets, received 19 out of 10 expected
Timed out waiting for data packets, received 20 out of 10 expected
```

The frames being from the containers sent contain the following data. Even though all streams share VLAN ID and PCP, each stream has a different source MAC (here frames 1 and 3 correspond to container A, and frames 2 and 4 correspond to container B):

```
10:36:01.800187 02:42:0a:00:65:61 > ac:1f:6b:1a:8a:fb, ethertype Unknown (0xdead), length 64:
        0x0000:  17ad 4225 4c06 7200 17ad 4225 2844 d979  ..B%L.r...B%(D.y
        0x0010:  0000 0006 dead beef dead beef dead beef  ................
        0x0020:  dead beef dead beef dead beef dead beef  ................
        0x0030:  dead                                     ..
10:36:01.800188 02:42:0a:00:65:60 > ac:1f:6b:1a:8a:fb, ethertype Unknown (0xdead), length 64:
        0x0000:  17ad 4225 4c06 7200 17ad 4225 2845 6694  ..B%L.r...B%(Ef.
        0x0010:  0000 0009 dead beef dead beef dead beef  ................
        0x0020:  dead beef dead beef dead beef dead beef  ................
        0x0030:  dead                                     ..
10:36:02.600186 02:42:0a:00:65:61 > ac:1f:6b:1a:8a:fb, ethertype Unknown (0xdead), length 64:
        0x0000:  17ad 4225 7bb5 7a00 17ad 4225 57f3 d63a  ..B%{.z...B%W..:
        0x0010:  0000 0007 dead beef dead beef dead beef  ................
        0x0020:  dead beef dead beef dead beef dead beef  ................
        0x0030:  dead                                     ..
10:36:02.600186 02:42:0a:00:65:60 > ac:1f:6b:1a:8a:fb, ethertype Unknown (0xdead), length 64:
        0x0000:  17ad 4225 7bb5 7a00 17ad 4225 57f4 7036  ..B%{.z...B%W.p6
        0x0010:  0000 000a dead beef dead beef dead beef  ................
        0x0020:  dead beef dead beef dead beef dead beef  ................
        0x0030:  dead 
```

Note that I get the same behavor if, instead of running `isochron send` in separate containers, I run them as just different processes in the host.

This is how I am running `isochron send`:

`isochron send --interface "$iface" --priority 1 --stats-port "$stats_port" --base-time 0 --shift-time 200000000 --cycle-time 0.8 --window-size 200000000 --num-frames 10 --frame-size 64 --client 10.0.101.133 --taprio --l2 --omit-sync -T`

Is it possible to use isochron to collect timestamps in the receiver from concurrent streams with the same source host, or is there a hardware timestaming limitation?

Thanks in advance.

**Comment by vladimiroltean** [comment]
Use a different ``--etype`` for each stream and it should work

**Comment by JorgeSasiain** [comment]
Like a charm, thank you for the quick reply!
